# Artificial Neural Network

### Kütüphanelerin İçeri Aktarılması

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## Part 1 - Veri Ön İşleme

### Veri Setinin İçeri Aktarılması

In [3]:
#Veri setini okuyarak bağımlı (X) ve bağımsız değişken (y) şekilinde ayırıyoruz.
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Veri Setinin Test ve Training Olarak Bölünmesi

In [5]:
#Veri setinin test ve train kümelerine bölüyoruz.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - ANN'nin İnşa Edilmesi



### ANN'yi Başlatma

In [6]:
#Tensorflow Keras API'si kullanılarak bir ANN modeli oluşturulur.
ann = tf.keras.models.Sequential()

### Giriş katmanın ve ilk gizli katmanın eklenmesi

In [7]:
#6 nöron ve ReLU aktivasyon fonksiyonunu kullanan bir katman oluşturulur.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### İkinci Gizli Katmanın Eklenmesi

In [8]:
#6 nöron ve ReLU aktivasyon fonksiyonunu kullanan ikinci gizli katman oluşturulur.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Çıkış Katmanının Eklenmesi

In [9]:
#Genellikle regresyon kullanıldığı zaman activation fonksiyonu seçilmez.
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - ANN'nin Eğitilmesi

### ANN'nin Derlenmesi

In [10]:
#En popüler optimize edici olan adam kullanılmakta
#loss, modelin eğitim sırasında optimizasyon algoritması tarafından minimize edilecek kayıp fonksiyonunu belirler.
ann.compile(optimizer='adam', loss='mean_squared_error')

### ANN'yi Test Verileri Üzerinde Eğitme

In [11]:
#Oluşturulan ANN eğitilir.
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
240/240 [==============================] - 3s 4ms/step - loss: 20027.6445
Epoch 2/50
240/240 [==============================] - 1s 3ms/step - loss: 300.7905
Epoch 3/50
240/240 [==============================] - 0s 2ms/step - loss: 288.7726
Epoch 4/50
240/240 [==============================] - 0s 2ms/step - loss: 273.9948
Epoch 5/50
240/240 [==============================] - 0s 2ms/step - loss: 257.0613
Epoch 6/50
240/240 [==============================] - 0s 2ms/step - loss: 238.0793
Epoch 7/50
240/240 [==============================] - 1s 2ms/step - loss: 218.1546
Epoch 8/50
240/240 [==============================] - 0s 2ms/step - loss: 197.4619
Epoch 9/50
240/240 [==============================] - 0s 2ms/step - loss: 176.7563
Epoch 10/50
240/240 [==============================] - 0s 2ms/step - loss: 155.8941
Epoch 11/50
240/240 [==============================] - 0s 2ms/step - loss: 136.7096
Epoch 12/50
240/240 [==============================] - 0s 2ms/step - loss: 118.1153

### Test Verilerine Göre Sonuçların Tahmin Edilmesi

In [12]:
#İlk sütun tahmin verilerini belirtir.
#İkinci sütun gerçek verileri belirtir.
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 2ms/step
[[431.01 431.23]
 [463.11 460.01]
 [467.15 461.14]
 ...
 [473.37 473.26]
 [441.94 438.  ]
 [460.41 463.28]]


## MAE - MSE - RMSE'nin Hesaplanması

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Ortalama Mutlak Hata (MAE) hesaplama
mae = mean_absolute_error(y_test, y_pred)
print("Ortalama Mutlak Hata (MAE):", mae)

# Ortalama Kare Hata (MSE) hesaplama
mse = mean_squared_error(y_test, y_pred)
print("Ortalama Kare Hata (MSE):", mse)

# Ortalama Kare Kök Hata (RMSE) hesaplama
rmse = np.sqrt(mse)
print("Ortalama Kare Kök Hata (RMSE):", rmse)

Ortalama Mutlak Hata (MAE): 4.011045477377833
Ortalama Kare Hata (MSE): 25.317962534708247
Ortalama Kare Kök Hata (RMSE): 5.031695791153142
